server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.159.128:8082/eureka/,http://192.168.159.128:8083/eureka/,http://192.168.159.128:8084/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: web-UI-Feign

##启用feign对hystrix的支持
#feign:
#  hystrix:
#    enabled: true