server:
  port: 8090
spring:
  application:
    name: zuul-Gateway

# routes to url
zuul:
  routes:
    api-client:
      path: /api-client/**
      serviceId: web-service

    api-ribbon:
      path: /api-ribbon/**
      serviceId: cloud-Ribbon

    api-feign:
      path: /api-feign/**
      serviceId: web-UI-Feign
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.159.128:8082/eureka/,http://192.168.159.128:8083/eureka/,http://192.168.159.128:8084/eureka/
##  instance:
#    preferIpAddress: true
