server:
  port: 9001
spring:
  application:
    name: cloud-Ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.159.128:8082/eureka/,http://192.168.159.128:8083/eureka/,http://192.168.159.128:8084/eureka/
  instance:
    preferIpAddress: true
